app: eventi
service: eventi
frameworkVersion: '^3'

provider:
  name: aws
  architecture: arm64
  runtime: provided.al2
  stage: dev
  region: ap-southeast-2

package:
  individually: true

functions:
    specific-schedule:
        handler: bootstrap
        package:
          artifact: deployable/specificschedule.zip
        events:
        - http:
            path: specific-schedule
            method: post
            cors: true